import {EventEmitter} from 'node:events';
import {spawn} from 'node:child_process';
import {createInterface} from 'node:readline';
import {randomUUID} from 'node:crypto';
import {existsSync,readFileSync,writeFileSync} from 'node:fs';
import {homedir,tmpdir} from 'node:os';
import path from 'node:path';
import {firstExisting,spawnCli} from './cli.js';

export const DSH_PREFIX='dsh:';
export const DSH_PROVIDER='deepseek-official';
export const DSH_ACP_VERSION=1;
// The DeepSeek Harness deployment catalog, used until a live session reports
// its own configuration options. `deepseek-flash` is the harness default and
// the model the office shows as DeepSeek-V41-Flash; the other entries are the
// adapter's advisory catalog shim. Unlisted ids still pass through to the
// gateway, so a newer node can be added without touching this list.
export const DSH_MODELS=[
  {id:'deepseek-flash',name:'DeepSeek-V41-Flash',description:'V4.1 Flash：多模态、长上下文，日常与并行任务的主力模型。'},
  {id:'deepseek-v4-flash',name:'DeepSeek-V4-Flash',description:'快速、经济的文本模型，适合明确的常规任务。'},
  {id:'deepseek-v4-pro',name:'DeepSeek-V4-Pro',description:'更强的代理编码与复杂推理，适合高要求任务。'},
  {id:'deepseek-v4-flash-vision-exp',name:'DeepSeek-V4-Flash-Vision-Exp',description:'实验性视觉模型。'}
];
const DSH_EFFORTS=[{reasoningEffort:'off'},{reasoningEffort:'low'},{reasoningEffort:'high'},{reasoningEffort:'max'}];
// Office effort names are Codex-shaped; the harness advertises off/low/high/max.
const EFFORT_NAMES={off:'off',low:'low',medium:'low',high:'high',xhigh:'max',max:'max',ultra:'max'};
const clip=(value,max)=>String(value??'').slice(0,max);
const textOf=content=>typeof content==='string'?content:typeof content?.text==='string'?content.text:Array.isArray(content)?content.map(textOf).join(''):'';
const outputOf=content=>Array.isArray(content)?content.map(part=>part?.type==='content'?textOf(part.content):part?.type==='diff'?`文件变更：${part.path||''}`:'').filter(Boolean).join('\n'):'';
const nativeId=id=>String(id||'').startsWith(DSH_PREFIX)?String(id).slice(DSH_PREFIX.length):String(id||'');
// ACP keeps the useful cause in the structured error payload; the top-level
// message alone ("Internal error") would hide why a session could not open.
const describeError=error=>{
  const detail=error?.data?.details??error?.data?.detail??(typeof error?.data==='string'?error.data:undefined);
  const message=error?.message||`DSH 返回错误 ${error?.code??'未知'}`;
  return detail&&!String(message).includes(detail)?`${message}：${detail}`:String(message);
};

// The DeepSeek Harness CLI is usually installed by Homebrew on macOS; on
// Windows it lands on PATH as dsh.exe/dsh.cmd. A launchd-managed service can
// carry a PATH that does not include it, so resolve a real binary up front and
// fall back to a plain PATH lookup when no known location exists.
export function resolveDshBinary(candidates=[process.env.OFFICE_DSH_BIN,'/opt/homebrew/bin/dsh','/usr/local/bin/dsh','/usr/bin/dsh',path.join(homedir(),'.dsh','bin','dsh')]){
  return firstExisting(candidates)||process.env.OFFICE_DSH_BIN||'dsh';
}

export const dshHome=()=>(process.env.DSH_HOME||'').trim()||path.join(homedir(),'.dsh');
// A deployment may pin its own overlay patches; `path.delimiter` keeps a list
// of files readable in one environment variable.
const envPatchFiles=()=>String(process.env.OFFICE_DSH_PATCH||'').split(path.delimiter).map(file=>file.trim()).filter(Boolean);
const CLIENT_UI_PREFIX='@dsh-external/dsh-client-ui';
// The home patch layer applies to every profile, but a client-UI skin is
// installed only for the surface that shows it, so an automation profile can
// fail to boot on an unresolvable skin package. Client-UI rows have no surface
// in an ACP run, so they are disabled through a generated overlay instead of
// editing the user's managed patch file; any other unresolvable home row keeps
// failing loudly rather than being silently dropped.
export function automationOverlay(homePatch=path.join(dshHome(),'cordis.patch.yml')){
  let text;try{text=readFileSync(homePatch,'utf8');}catch{return null;}
  const ids=[];let previousId=null;
  for(const line of text.split('\n')){
    const entry=line.trim();if(!entry||entry.startsWith('#'))continue;
    const id=entry.match(/^-\s*id:\s*['"]?([A-Za-z0-9._@/-]+?)['"]?$/);
    if(id){previousId=id[1];continue;}
    const name=entry.match(/^name:\s*['"]?([^'"\s]+?)['"]?$/);
    if(name&&previousId&&name[1].startsWith(CLIENT_UI_PREFIX))ids.push(previousId);
    previousId=null;
  }
  const rows=[...new Set(ids)];
  if(!rows.length)return null;
  return ['# Generated by 待命室 for `dsh --profile acp`: client-UI rows inserted by the','# home patch layer have no surface in an automation profile.','',...rows.flatMap(id=>[`- id: ${id}`,'  disabled: true']),''].join('\n');
}

// ACP stdio MCP entries carry the environment as name/value pairs; the office
// member descriptor also carries Codex/ZCode-only fields that ACP rejects.
function acpMcpServers(servers=[]){
  return servers.map(server=>({name:server.name,command:server.command,args:server.args||[],env:(server.env||[]).map(({name,value})=>({name,value}))}));
}

// Bridge from `dsh --profile acp` (standard ACP v1 over newline-delimited
// JSON-RPC on stdio) to the office App Server event contract. Each office
// thread is one persistent harness session in one long-lived child process;
// a turn is one `session/prompt`, and committed assistant/tool updates are
// folded back into the office notification vocabulary. ACP owns no steering
// surface, so a mid-turn supplement is refused instead of silently dropped.
export class DshBridge extends EventEmitter {
  constructor({cwd=process.cwd(),binary=resolveDshBinary(),profile=process.env.OFFICE_DSH_PROFILE||'acp',permissionMode=process.env.OFFICE_DSH_PERMISSION_MODE||'',patchFiles=envPatchFiles(),overlayClientUi=true,overlayDir=tmpdir(),models=DSH_MODELS,requestTimeoutMs=60000,sessionTimeoutMs=120000,restartThrottleMs=60000,spawnProcess=spawn}={}){
    super();this.cwd=cwd;this.binary=binary;this.profile=profile;this.permissionMode=permissionMode;this.patchFiles=patchFiles;this.overlayClientUi=overlayClientUi;this.overlayDir=overlayDir;this.models=models;this.requestTimeoutMs=requestTimeoutMs;this.sessionTimeoutMs=sessionTimeoutMs;this.restartThrottleMs=restartThrottleMs;this.spawnProcess=spawnProcess;
    this.pending=new Map();this.clientRequests=new Map();this.sessions=new Map();this.aliases=new Map();this.liveModels=new Map();this.sequence=0;this.ready=false;this.child=null;this.starting=null;this.lastStartAttempt=0;this.stderr='';this.agentInfo=null;
  }
  // Overlay patches ride on the command line, so they are rebuilt per boot and
  // follow a skin switch in the user's home layer without touching their file.
  patchArguments(){
    if(this.patchFiles.length)return this.patchFiles.flatMap(file=>['--patch',file]);
    if(!this.overlayClientUi)return [];
    const overlay=automationOverlay();
    if(!overlay)return [];
    const file=path.join(this.overlayDir,`office-dsh-automation-${this.profile}.patch.yml`);
    try{writeFileSync(file,overlay,{mode:0o600});}catch{return [];}
    return ['--patch',file];
  }
  start(){
    if(this.ready)return Promise.resolve();
    if(this.starting)return this.starting;
    this.lastStartAttempt=Date.now();
    this.starting=this.connect().catch(error=>{this.child?.kill();throw error;}).finally(()=>{this.starting=null;});
    return this.starting;
  }
  // A manual reconnect drops the child and tells the office every thread is
  // unloaded, so the next launch resumes its persisted harness session.
  restart(){this.close('DSH 运行环境正在重启');this.ready=false;this.child=null;return this.start();}
  // Runtime liveness for the periodic reconcile in OfficeRuntimes: a dead child
  // is reconnected at most once a minute so a broken install cannot spin.
  async pollStatus(){
    if(this.ready&&this.child)return {connected:true,authenticated:true,message:'已连接'};
    if(!this.child&&!this.starting&&Date.now()-this.lastStartAttempt>this.restartThrottleMs){try{await this.start();}catch{}}
    if(this.ready&&this.child)return {connected:true,authenticated:true,message:'已连接'};
    return {connected:!!this.child,authenticated:false,message:this.stderr?`DSH 启动失败：${clip(this.stderr,300)}`:'DSH 未连接，等待本机 dsh 运行环境'};
  }
  async connect(){
    const args=['--profile',this.profile,...this.patchArguments()];
    const env={...process.env};if(this.permissionMode)env.DSH_PERMISSION_MODE=this.permissionMode;
    if(path.isAbsolute(this.binary)&&!existsSync(this.binary))throw new Error(`未找到 DSH 运行程序（${this.binary}），可设置 OFFICE_DSH_BIN 指向本机 dsh。`);
    const child=spawnCli(this.spawnProcess,this.binary,args,{cwd:this.cwd,stdio:['pipe','pipe','pipe'],env});this.child=child;this.stderr='';
    const disconnected=message=>{
      if(this.child!==child)return;
      this.ready=false;this.child=null;
      for(const entry of this.pending.values()){clearTimeout(entry.timer);entry.reject(new Error(message));}
      this.pending.clear();this.clientRequests.clear();
      for(const session of this.sessions.values()){session.turnId=null;session.prompt=null;}
      this.emit('disconnected',message);
    };
    child.on('error',error=>disconnected(`无法启动 DSH：${error.message}`));
    child.on('exit',(code,signal)=>disconnected(`DSH 连接已关闭（${signal||code}）`));
    child.stdin.on('error',()=>{});
    child.stderr.on('data',chunk=>{this.stderr=clip(this.stderr+chunk,4000);});
    createInterface({input:child.stdout}).on('line',line=>this.handleLine(line));
    const handshake=await this.rpc('initialize',{protocolVersion:DSH_ACP_VERSION,clientCapabilities:{fs:{readTextFile:false,writeTextFile:false},terminal:false},clientInfo:{name:'readyroom',version:'0.3.0'}},this.sessionTimeoutMs);
    this.agentInfo=handshake?.agentInfo||null;
    this.ready=true;this.emit('connected');
  }
  send(message){if(!this.child?.stdin.writable)throw new Error('DSH 尚未连接');this.child.stdin.write(JSON.stringify(message)+'\n');}
  rpc(method,params={},timeout=this.requestTimeoutMs){
    return new Promise((resolve,reject)=>{
      const id=++this.sequence,timer=timeout>0?setTimeout(()=>{this.pending.delete(id);reject(new Error(`DSH 请求超时：${method}`));},timeout):null;
      this.pending.set(id,{resolve,reject,timer});
      try{this.send({jsonrpc:'2.0',id,method,params});}catch(error){if(timer)clearTimeout(timer);this.pending.delete(id);reject(error);}
    });
  }
  notify(method,params={}){this.send({jsonrpc:'2.0',method,params});}
  handleLine(line){
    let message;try{message=JSON.parse(line);}catch{return;}
    if(message.method!==undefined){if(message.id!==undefined)this.handleClientRequest(message);else this.handleNotification(message);return;}
    const entry=this.pending.get(message.id);if(!entry)return;
    if(entry.timer)clearTimeout(entry.timer);this.pending.delete(message.id);
    message.error?entry.reject(new Error(describeError(message.error))):entry.resolve(message.result);
  }
  session(id){
    const key=nativeId(id),session=this.sessions.get(key)||this.sessions.get(this.aliases.get(key));
    if(!session)throw new Error('DSH 会话尚未建立');return session;
  }
  // `session/new` publishes the live configuration options; every later
  // selection teaches the bridge the catalog the running deployment offers.
  learn(configOptions=[]){
    for(const option of configOptions||[]){
      if(option?.id!=='model'||!Array.isArray(option.options))continue;
      for(const group of option.options)for(const entry of group?.options||[]){
        let selection;try{selection=JSON.parse(entry.value);}catch{continue;}
        if(!Array.isArray(selection)||selection.length!==2)continue;
        this.liveModels.set(selection[1],{id:selection[1],name:entry.name||selection[1],...(entry.description?{description:entry.description}:{})});
      }
    }
  }
  catalog(){
    const merged=new Map(this.models.map(model=>[model.id,{...model}]));
    for(const [id,model] of this.liveModels)merged.set(id,{...merged.get(id),...model});
    return [...merged.values()].map(model=>({model:model.id,displayName:`${model.name}（DSH）`,provider:'dsh',supportedReasoningEfforts:DSH_EFFORTS}));
  }
  async applyModel(session,model,effort){
    if(!model)return;
    let options;
    try{options=await this.rpc('session/set_config_option',{sessionId:session.id,configId:'model',value:JSON.stringify([DSH_PROVIDER,model])},this.sessionTimeoutMs);}
    catch(error){throw new Error(`DSH 无法选择模型 ${model}：${error.message}`);}
    this.learn(options?.configOptions);session.model=model;
    const reasoning=EFFORT_NAMES[effort];
    if(!reasoning)return;
    try{this.learn((await this.rpc('session/set_config_option',{sessionId:session.id,configId:'reasoning_effort',value:reasoning},this.sessionTimeoutMs))?.configOptions);}
    catch{} // A model without an advertised effort selector keeps its own default.
  }
  async request(method,params={}){
    if(method==='account/read')return {account:this.ready?{type:'dsh-acp'}:null};
    if(method==='model/list')return {data:this.catalog()};
    if(!this.ready)throw new Error(this.stderr?`DSH 尚未连接：${clip(this.stderr,300)}`:'DSH 尚未连接，请确认本机 dsh 可用');
    if(method==='thread/start'||method==='thread/resume')return this.startThread(method,params);
    if(method==='thread/name/set')return {}; // ACP exposes no title surface; the office keeps its own names.
    if(method==='turn/start')return this.startTurn(params);
    if(method==='turn/steer')throw new Error('DSH 正在生成本轮回复；请等本轮结束后再补充要求。');
    if(method==='turn/interrupt')return this.interrupt(params);
    throw new Error(`DSH 不支持此待命室操作：${method}`);
  }
  async startThread(method,params){
    const cwd=params.cwd;
    if(typeof cwd!=='string'||!path.isAbsolute(cwd))throw new Error('DSH 会话需要绝对工作目录。');
    const mcpServers=acpMcpServers(params.officeMcpServers||[]);
    let sessionId,configOptions;
    if(method==='thread/start'){
      const created=await this.rpc('session/new',{cwd,mcpServers},this.sessionTimeoutMs);
      sessionId=created.sessionId;configOptions=created.configOptions;
    }else{
      const requested=nativeId(params.threadId);
      if(!requested)throw new Error('DSH 会话缺少会话 ID，无法恢复。');
      try{
        const resumed=await this.rpc('session/resume',{sessionId:requested,cwd,mcpServers},this.sessionTimeoutMs);
        sessionId=requested;configOptions=resumed?.configOptions;
      }catch(error){
        // A pruned or foreign harness session must not strand the office
        // member: open a fresh session under the same office thread id and say
        // so in the mission log instead of failing the launch.
        const created=await this.rpc('session/new',{cwd,mcpServers},this.sessionTimeoutMs);
        sessionId=created.sessionId;configOptions=created.configOptions;
        this.aliases.set(requested,sessionId);
        this.emit('notification',{method:'error',params:{threadId:DSH_PREFIX+requested,error:{message:`原 DSH 会话无法恢复（${clip(error.message,200)}），已新建会话继续；本轮会重新读取任务上下文。`}}});
      }
    }
    const session={id:sessionId,cwd,model:null,instructions:clip(params.developerInstructions||'',24000),turnId:null,prompt:null,stopping:false,messages:new Map(),tools:new Map()};
    this.sessions.set(sessionId,session);
    this.learn(configOptions);
    await this.applyModel(session,params.model,params.officeEffort||params.effort);
    return {thread:{id:DSH_PREFIX+sessionId},model:session.model,provider:'dsh'};
  }
  startTurn(params){
    const session=this.session(params.threadId);
    if(session.turnId)throw new Error('该 DSH 成员已有任务在执行');
    const text=(params.input||[]).filter(item=>item.type==='text').map(item=>item.text).join('\n');
    if(!text.trim())throw new Error('DSH 收到空消息');
    const turnId='dturn_'+randomUUID();
    session.turnId=turnId;session.stopping=false;session.messages.clear();session.tools.clear();
    const content=`${session.instructions}${session.instructions?'\n\n':''}本轮任务：\n${text}`;
    session.prompt=this.rpc('session/prompt',{sessionId:session.id,prompt:[{type:'text',text:content}]},0)
      .then(result=>this.settle(session,turnId,result))
      .catch(error=>this.settle(session,turnId,null,error));
    return {turn:{id:turnId}};
  }
  settle(session,turnId,result,error){
    if(session.turnId!==turnId)return;
    const stop=result?.stopReason,interrupted=session.stopping||stop==='cancelled';
    const status=interrupted?'interrupted':error||stop==='refusal'?'failed':'completed';
    const message=error?clip(error.message||'DSH 执行失败',400):stop==='max_tokens'?'达到模型最大输出长度，本轮已结束':null;
    const items=[...session.messages.entries()].filter(([,text])=>text.trim()).map(([id,text])=>({id,type:'agentMessage',phase:'final_answer',text}));
    session.turnId=null;session.prompt=null;session.stopping=false;
    this.emit('notification',{method:'turn/completed',params:{threadId:DSH_PREFIX+session.id,turnId,turn:{id:turnId,status,error:message?{message}:null,items}}});
  }
  async interrupt(params){
    const key=nativeId(params.threadId),session=this.sessions.get(key)||this.sessions.get(this.aliases.get(key));
    if(!session||!session.turnId||session.turnId!==params.turnId)return {};
    session.stopping=true;this.notify('session/cancel',{sessionId:session.id});return {};
  }
  emitEvent(session,method,params){this.emit('notification',{method,params:{threadId:DSH_PREFIX+session.id,turnId:session.turnId,...params}});}
  // ACP reports committed facts, not provider deltas: one assistant message
  // usually arrives as a single chunk, and a tool call as start then finish.
  handleNotification(message){
    if(message.method!=='session/update')return;
    const {sessionId,update}=message.params||{},session=this.sessions.get(sessionId);
    if(!session||!update)return;
    if(update.sessionUpdate==='agent_message_chunk'){
      const text=textOf(update.content);if(!text)return;
      const itemId=update.messageId||'agent-message';
      session.messages.set(itemId,(session.messages.get(itemId)||'')+text);
      this.emitEvent(session,'item/agentMessage/delta',{itemId,delta:text});return;
    }
    if(update.sessionUpdate==='tool_call'){
      const name=String(update.title||'工具');
      session.tools.set(update.toolCallId,{name,kind:update.kind,input:update.rawInput});
      const item=this.toolItem(update.toolCallId,update,{status:'inProgress'});
      this.emitEvent(session,'item/started',{item});return;
    }
    if(update.sessionUpdate==='tool_call_update'){
      const known=session.tools.get(update.toolCallId)||{name:'工具'};
      const item=this.toolItem(update.toolCallId,{...update,title:update.title||known.name,kind:update.kind||known.kind,rawInput:update.rawInput??known.input},{status:update.status==='failed'?'failed':'completed'});
      item.aggregatedOutput=outputOf(update.content);
      this.emitEvent(session,'item/completed',{item});return;
    }
    if(update.sessionUpdate==='usage_update'&&Number.isFinite(update.used)){
      this.emitEvent(session,'thread/tokenUsage/updated',{tokenUsage:{total:{inputTokens:0,outputTokens:0,cachedInputTokens:0,totalTokens:update.used}}});return;
    }
  }
  // ACP tool kinds are generic; the office distinguishes commands, file edits
  // and collaboration tool calls for its execution log and file list.
  toolItem(id,update,{status}){
    const kind=update.kind,name=String(update.title||'工具'),input=update.rawInput;
    const file=['edit','delete','move'].includes(kind);
    const command=kind==='execute'||typeof input?.command==='string';
    const item={id,type:file?'fileChange':command?'commandExecution':'mcpToolCall',tool:name,status};
    if(item.type==='commandExecution')item.command=clip(typeof input==='string'?input:input?.command||name,4000);
    if(item.type==='fileChange')item.changes=[{path:clip(filePath(update)||name,1000),kind:kind==='delete'?'delete':kind==='edit'?'update':'update',diff:''}];
    return item;
  }
  handleClientRequest(message){
    const params=message.params||{},session=this.sessions.get(params.sessionId);
    if(message.method==='session/request_permission'){
      if(!session){this.send({jsonrpc:'2.0',id:message.id,result:{outcome:{outcome:'cancelled'}}});return;}
      const tool=params.toolCall||{},options=params.options||[],allow=options.find(option=>String(option.kind||'').startsWith('allow')),reject=options.find(option=>String(option.kind||'').startsWith('reject'));
      const id='dreq_'+message.id,input=tool.rawInput;
      // A shell approval reads best as the command itself; anything else keeps
      // the full tool input so the user can judge what will run.
      const command=typeof input==='string'?input:typeof input?.command==='string'?input.command:JSON.stringify(input??tool.title??'工具调用',null,2);
      this.clientRequests.set(id,{id:message.id,allow:allow?.optionId||'allow-once',reject:reject?.optionId||'reject-once'});
      this.emit('request',{id,method:'item/commandExecution/requestApproval',params:{threadId:DSH_PREFIX+session.id,turnId:session.turnId,itemId:tool.toolCallId,reason:clip(tool.title||'DSH 需要你授权这项操作',400),command:clip(command,4000),cwd:session.cwd,availableDecisions:['accept','decline'],isBlocking:true}});return;
    }
    this.send({jsonrpc:'2.0',id:message.id,error:{code:-32601,message:`Office host does not provide ${message.method}`}});
  }
  respond(id,result){
    const entry=this.clientRequests.get(id);if(!entry)return;this.clientRequests.delete(id);
    const optionId=result?.decision==='accept'?entry.allow:entry.reject;
    this.send({jsonrpc:'2.0',id:entry.id,result:{outcome:{outcome:'selected',optionId}}});
  }
  reject(id){
    const entry=this.clientRequests.get(id);if(!entry)return;this.clientRequests.delete(id);
    this.send({jsonrpc:'2.0',id:entry.id,result:{outcome:{outcome:'cancelled'}}});
  }
  close(reason){
    this.ready=false;this.sessions.clear();this.aliases.clear();this.clientRequests.clear();
    const child=this.child;this.child=null;child?.kill('SIGTERM');
    if(reason)this.emit('disconnected',reason);
  }
}
// ACP file locations are the portable way to name the touched file; raw tool
// input is the fallback for harness tools that report a path directly.
function filePath(update){
  const locations=Array.isArray(update.locations)?update.locations:[],input=update.rawInput;
  return locations[0]?.path||(typeof input?.path==='string'?input.path:typeof input?.file_path==='string'?input.file_path:undefined);
}
