import {localFileLink} from './document-links.js';
import {teamMember} from './team.js';
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const states={waiting_input:'等待输入',ready:'就绪排队',suspending:'等待轮次结束',suspended:'已挂起',queued:'等待开始',starting:'准备中',running:'执行中',waiting:'等待答复',completed:'已结束',failed:'失败',stopped:'已停止',interrupted:'已中断'};
const duration=ms=>ms<1000?'不足 1 秒':ms<60000?`${Math.floor(ms/1000)} 秒`:`${Math.floor(ms/60000)} 分 ${Math.floor(ms%60000/1000)} 秒`;
const roleNames=roles=>(roles||[]).map(r=>escape(teamMember(r)?.shortPosition||r)).join(' / ');
export function collaborationUsage(m){
  if(!m?.harnessVersion)return null;
  const works=(m.workItems||[]).filter(w=>w.protocol===2),attempts=works.flatMap(w=>w.attempts||[]),sources=[m.agents.find(a=>a.id===m.coordinatorId)?.usage,...attempts.map(a=>a.usage)].filter(Boolean);
  return {tasks:works.length,attempts:attempts.length,reported:sources.length,totalTokens:sources.reduce((n,u)=>n+(u.totalTokens||0),0),cachedInputTokens:sources.reduce((n,u)=>n+(u.cachedInputTokens||0),0),outputTokens:sources.reduce((n,u)=>n+(u.outputTokens||0),0)};
}
function timing(w,now){
  if(w.protocol!==2)return '';
  const times={...w.timings};if(['waiting_input','ready','starting','running','waiting','suspending','suspended'].includes(w.status))times[w.status]=(times[w.status]||0)+Math.max(0,now-(Date.parse(w.stateSince||w.createdAt)||now));
  const waits={...w.waitTimings};if(w.waitReason?.kind)waits[w.waitReason.kind]=(waits[w.waitReason.kind]||0)+Math.max(0,now-(Date.parse(w.waitSince)||now));
  return `<div class="work-timing">输入等待 ${duration((times.waiting_input||0)+(times.suspended||0))} · 就绪排队 ${duration((times.ready||0)+(times.queued||0))} · 执行 ${duration((times.starting||0)+(times.running||0)+(times.waiting||0)+(times.suspending||0))} · 第 ${w.generation||0} 代 / 重试 ${w.retries||0}<br>范围等待 ${duration(waits.scope||0)} · 资源等待 ${duration(waits.resource||0)} · 模型排队 ${duration(waits.model||0)} · 工具等待 ${duration(waits.tool||0)}</div>${w.timeline?.length?`<details class="work-inputs"><summary>状态与等待记录</summary><ol>${w.timeline.slice(-20).map(e=>`<li>${escape(e.at.slice(11,19))} · ${escape(e.message||states[e.status]||e.status)}${e.generation?` · 第 ${e.generation} 代`:''}</li>`).join('')}</ol></details>`:''}`;
}
export function collaborationPanel(m,nameOf=id=>id){
  if(!m.workItems?.length)return '';
  const works=m.workItems.filter(w=>!w.replacedBy),running=works.filter(w=>['starting','running','waiting','suspending'].includes(w.status)).length;
  const issues=m.quality?.issues||[],passed=m.quality?.status==='passed',now=Date.now();
  const paths=items=>items.length?items.map(escape).join('、'):'无';
  const workName=id=>escape(m.workItems.find(w=>w.id===id)?.key||id),metrics=m.harnessMetrics;
  const graph=m.harnessVersion?`<div class="harness-overview"><strong>按输入就绪调度</strong><span>${metrics?.ready??works.filter(w=>w.status==='ready').length} 项就绪 · ${metrics?.waiting??works.filter(w=>['waiting_input','suspended'].includes(w.status)).length} 项等输入 · ${metrics?.completed??works.filter(w=>w.status==='completed').length}/${works.length} 项证据通过</span></div><p>规划者定目标与依赖；空闲合适成员领取工作。等输入不占人物；实际轮次结束才释放模型名额。阶段契约按固定版本交接。</p>${m.artifactVersions?.length?`<details class="harness-artifacts"><summary>阶段契约 · ${m.artifactVersions.length} 个固定版本</summary>${m.artifactVersions.map(v=>`<div><b>${escape(v.name)}:${escape(v.version)}</b> · ${v.status==='validated'?'独立验证通过':'已发布，待验证'}<small>SHA-256 ${escape(v.digest)}</small><span>${escape(v.summary)}</span></div>`).join('')}</details>`:''}`:'<p>独立范围并行，重叠读写等待；写入成果由另一位成员复核。</p>';
  return `<section class="collaboration-board"><div class="collaboration-heading"><h3>协作分工与验收</h3><span>${running} 人执行 · ${passed?'证据齐备':'待验证'}</span></div>${graph}${issues.length?`<details class="quality-issues"><summary>验收待补全 · ${issues.length} 项</summary><ul>${issues.map(issue=>`<li>${escape(issue)}</li>`).join('')}</ul></details>`:''}${works.map(w=>`<details class="collaboration-work" data-work-id="${escape(w.id)}"><summary><strong>${escape(w.key||(w.agentId?nameOf(w.agentId):'待领取'))} · ${w.reviewOf.length?'独立复核':w.scope.writePaths.length?'执行产出':'只读调研'}</strong><span>${escape(states[w.status]||w.status)}${w.stale?' · 复核已过期':''}</span></summary>${w.waitReason?`<p class="work-blocker">${escape(w.waitReason.message)}</p>`:''}<div class="work-scope"><small>${escape(w.id)}</small>${w.protocol===2?`<div>领取：${w.agentId?escape(nameOf(w.agentId)):'尚未占用人物'} · 适配：${roleNames(w.eligibleRoles)}</div>`:''}<p>${escape(w.task)}</p><div>读取：${paths(w.scope.readPaths)}</div><div>写入：${paths(w.scope.writePaths)}</div>${w.dependsOn.length?`<div>完成依赖：${w.dependsOn.map(workName).join('、')}</div>`:''}${w.requires?.length?`<div>输入版本：${w.requires.map(r=>`${escape(r.name)}:${escape(r.version)}（${r.status==='published'?'发布快照':'验证通过'}）`).join('、')}</div>`:''}${w.inputs?.length?`<details class="work-inputs"><summary>本代固定输入</summary>${w.inputs.map(v=>`<div>${escape(v.name)}:${escape(v.version)}<small>SHA-256 ${escape(v.digest)}</small></div>`).join('')}</details>`:''}${w.produces?.length?`<div>阶段产出：${w.produces.map(r=>`${escape(r.name)}:${escape(r.version)}`).join('、')}</div>`:''}${w.resources?.length?`<div>预约资源：${w.resources.map(r=>`${escape(r.name)} × ${r.units}/${r.capacity}`).join('、')}</div>`:''}${w.reviewOf.length?`<div>复核：${w.reviewOf.map(workName).join('、')}</div>`:''}${w.checkpoint?`<div>恢复检查点：${escape(w.checkpoint)}</div>`:''}${timing(w,now)}${w.acceptance.length?`<ol>${w.acceptance.map(c=>`<li>${escape(c)}</li>`).join('')}</ol>`:''}${w.report?`<div class="work-report"><b>${w.report.verdict==='ready'?'已提交证据':'报告有阻塞'}</b><p>${escape(w.report.summary)}</p>${w.report.artifacts.length?`<p>成果：${w.report.artifacts.map(file=>localFileLink(m.id,file,file)).join('、')}</p>`:''}<ul>${w.report.checks.map(c=>`<li>${c.result==='passed'?'✓':c.result==='failed'?'✗':'○'} ${escape(c.name)}<pre>${escape(c.evidence)}</pre></li>`).join('')}</ul>${w.report.risks.length?`<p>风险：${w.report.risks.map(escape).join('；')}</p>`:''}</div>`:'<p>尚未提交交付报告</p>'}</div></details>`).join('')}</section>`;
}
