import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {CUSTOM_CHARACTERS} from './assets/custom-cast.js';
import {seatedLifeClip} from './assets/seated-life.js';

const $=selector=>document.querySelector(selector),qa=window.__narutoPreview,stage=$('#stage');
const query=new URLSearchParams(location.search),character=CUSTOM_CHARACTERS.find(item=>item.id===query.get('character'))||CUSTOM_CHARACTERS[0];
const version=query.get('v')||character.modelRevision,modelURL=`/assets/characters/custom/${character.id}_chibi_custom.glb?v=${encodeURIComponent(version)}`;
if(query.get('embed')==='1')document.body.classList.add('preview-embedded');
qa.character=character.id;document.title=`${character.name} · 角色工作室`;
$('.viewer').setAttribute('aria-label',`${character.name} 3D 角色预览`);
$('.scene-title h1').innerHTML=`${character.title}<span style="color:${character.color}">.</span>`;
$('.scene-title .sub').textContent=`${character.fullName} · Q 版角色`;
$('.scene-title .eyebrow').textContent=`KONOHA COLLECTION / 0${CUSTOM_CHARACTERS.indexOf(character)+1}`;
$('.character-name h2').textContent=character.fullName;$('.character-name p').textContent=character.subtitle;
$('.character-description').textContent=character.description;
for(const option of $('#animation').options)if(character.animationLabels?.[option.value])option.textContent=character.animationLabels[option.value];
$('.character-type span').textContent='木叶 · Q 版人物';
const palettes={naruto:{colors:['#e6b837','#e8792d','#273644','#edc4a1','#aeb7b5'],label:'阳光金 · 忍者橙 · 深海蓝'},hiruzen:{colors:['#d36d63','#eee9dc','#36343a','#c9beb3','#b59783'],label:'火影红 · 米白 · 炭灰'},tsunade:{colors:['#e0cc87','#799777','#e6e1d4','#344358','#987bb4'],label:'浅金 · 羽织绿 · 紫额印'},sakura:{colors:['#e4a9ba','#c35379','#b4bf83','#35313b','#f0d6c5'],label:'樱花粉 · 玫红 · 叶绿'},mizukage:{colors:['#9c5a48','#568293','#8fb6a4','#f0d6c2','#2f3a40'],label:'赤棕长发 · 水纹青碧 · 雾隐绿'}};
const palette=palettes[character.id];$('.palette').innerHTML=palette.colors.map(color=>`<i style="background:${color}"></i>`).join('');$('.palette').setAttribute('aria-label',palette.label);$('.palette-label').textContent=palette.label;
$('#character').innerHTML=CUSTOM_CHARACTERS.map(item=>`<option value="${item.id}">${item.name}</option>`).join('');$('#character').value=character.id;
$('#character').onchange=()=>{const url=new URL(location.href);url.searchParams.set('character',$('#character').value);url.searchParams.delete('v');location.href=url.href;};
$('#download').download=`${character.id}_chibi_custom.glb`;
qa.modelURL=modelURL;qa.clipNames=[];qa.availableAnimations=[];qa.currentAnimation=null;qa.desiredAnimation='Idle';qa.paused=false;qa.view='front';
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(31,1,.01,100);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.06;renderer.outputColorSpace=THREE.SRGBColorSpace;
const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();scene.environment=pmrem.fromScene(room,.055).texture;scene.environmentIntensity=.3;room.dispose();pmrem.dispose();
renderer.domElement.setAttribute('aria-label',`可旋转、缩放的${character.name}三维模型`);renderer.domElement.setAttribute('role','img');stage.append(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.075;controls.enablePan=false;controls.autoRotateSpeed=.8;controls.maxPolarAngle=Math.PI*.56;controls.minPolarAngle=.20;
const hemisphere=new THREE.HemisphereLight('#fff7e5','#adb2aa',1.5);scene.add(hemisphere);
const keyLight=new THREE.DirectionalLight('#fff1d9',2.4);keyLight.position.set(-3.8,7,5);keyLight.castShadow=true;keyLight.shadow.mapSize.set(2048,2048);Object.assign(keyLight.shadow.camera,{left:-4,right:4,top:5,bottom:-4,near:.1,far:20});keyLight.shadow.normalBias=.012;keyLight.shadow.bias=-.0001;keyLight.shadow.radius=4;scene.add(keyLight);
const fill=new THREE.DirectionalLight('#dceafa',1.1);fill.position.set(4,3,3);scene.add(fill);
const rim=new THREE.DirectionalLight('#ffefc9',1.8);rim.position.set(2,5,-4);scene.add(rim);
const ground=new THREE.Mesh(new THREE.CircleGeometry(20,96),new THREE.ShadowMaterial({color:'#6e7666',opacity:.23}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;ground.position.y=.004;scene.add(ground);
const pedestal=new THREE.Mesh(new THREE.CylinderGeometry(1.02,1.02,.055,96),new THREE.MeshStandardMaterial({color:'#e9e8de',roughness:.92}));pedestal.position.y=-.03;pedestal.receiveShadow=true;scene.add(pedestal);
const outline=new THREE.Mesh(new THREE.RingGeometry(1.15,1.154,120),new THREE.MeshBasicMaterial({color:'#d4d9c8',transparent:true,opacity:.58,side:THREE.DoubleSide}));outline.rotation.x=-Math.PI/2;outline.position.y=.008;scene.add(outline);
let model,mixer,action,clips=new Map(),paused=false,desired='Idle',height=3,width=1.5,loaded=false,activeView=query.get('view')==='three-quarter'?'three-quarter':'front',last=performance.now(),transition=false,procedural=false;
const renderTarget=new THREE.Vector3(),directions={front:[0,.11,1],'three-quarter':[.66,.15,.75],side:[1,.11,0],back:[0,.11,-1]};
let cameraDestination=null,targetDestination=null;
function fail(error){qa.ready=false;qa.status='error';const message=String(error?.message||error);if(!qa.errors.includes(message))qa.errors.push(message);$('#loading').hidden=false;$('#loading').classList.add('error');$('#loading-message').textContent='暂时无法打开模型';$('#loading-detail').textContent=message;$('#retry').hidden=false;console.error(error);}
function framing(){const aspect=stage.clientWidth/Math.max(1,stage.clientHeight),vertical=height*.64/Math.tan(THREE.MathUtils.degToRad(camera.fov/2)),horizontal=(Math.max(width,height*.46)*.67)/(Math.tan(THREE.MathUtils.degToRad(camera.fov/2))*aspect);return Math.max(vertical,horizontal);}
function setView(name,immediate=false){if(!directions[name])return false;activeView=name;qa.view=name;controls.autoRotate=false;$('#auto-rotate').setAttribute('aria-checked','false');const d=framing(),vector=new THREE.Vector3(...directions[name]).normalize();renderTarget.set(0,height*.48,0);cameraDestination=renderTarget.clone().addScaledVector(vector,d);targetDestination=renderTarget.clone();if(immediate){camera.position.copy(cameraDestination);controls.target.copy(targetDestination);cameraDestination=null;targetDestination=null;controls.update();}for(const b of document.querySelectorAll('[data-view]'))b.setAttribute('aria-pressed',String(b.dataset.view===name));return true;}
function actualClip(name){const mapped=character.previewClips?.[name]??name;if(clips.has(mapped))return mapped;if(name==='Sitting'&&clips.has('Sit'))return 'Sit';return null;}
function play(name,once=false){const actual=actualClip(name);if(!actual||!mixer)return false;const previous=action,next=mixer.clipAction(clips.get(actual));next.reset().setEffectiveTimeScale(1).setEffectiveWeight(1).setLoop(once?THREE.LoopOnce:THREE.LoopRepeat,once?1:Infinity);next.clampWhenFinished=once;next.play();if(previous&&previous!==next)next.crossFadeFrom(previous,.2,false);action=next;transition=once;qa.currentAnimation=actual;qa.transitioning=once;stage.dataset.animation=actual;return true;}
const isSeated=name=>['Sitting','Typing','Sit',character.previewClips?.Sitting].includes(name);
function selectAnimation(name){if(!actualClip(name))return false;desired=name;qa.desiredAnimation=name;$('#animation-notice').textContent=name==='Sitting'&&!character.previewClips?.Sitting?'自然休息：轻微呼吸、左右张望、低头思考和放松肩膀。':character.animationNotice||'可预览待机、行走、入座与打字';$('#animation').value=name;paused=false;qa.paused=false;$('#pause').textContent='Ⅱ';$('#pause').setAttribute('aria-label','暂停动画');$('#pause').setAttribute('aria-pressed','false');if(transition)return true;const now=qa.currentAnimation;if(isSeated(name)&&!isSeated(now)&&clips.has('SitDown'))play('SitDown',true);else if(!isSeated(name)&&isSeated(now)&&clips.has('StandUp'))play('StandUp',true);else play(name);return true;}
function setPaused(value){paused=Boolean(value);qa.paused=paused;$('#pause').textContent=paused?'▷':'Ⅱ';$('#pause').setAttribute('aria-label',paused?'继续动画':'暂停动画');$('#pause').setAttribute('aria-pressed',String(paused));return paused;}
function setAutoRotate(value){controls.autoRotate=Boolean(value);qa.autoRotate=controls.autoRotate;$('#auto-rotate').setAttribute('aria-checked',String(controls.autoRotate));cameraDestination=null;targetDestination=null;if(value){qa.view='orbit';for(const b of document.querySelectorAll('[data-view]'))b.setAttribute('aria-pressed','false');}return controls.autoRotate;}
$('#animation').addEventListener('change',e=>selectAnimation(e.target.value));$('#pause').addEventListener('click',()=>setPaused(!paused));$('#auto-rotate').addEventListener('click',()=>setAutoRotate(!controls.autoRotate));$('#shadows').addEventListener('click',()=>{ground.visible=!ground.visible;renderer.shadowMap.enabled=ground.visible;$('#shadows').setAttribute('aria-checked',String(ground.visible));});$('#retry').addEventListener('click',()=>location.reload());
for(const button of document.querySelectorAll('[data-view]'))button.addEventListener('click',()=>setView(button.dataset.view));
controls.addEventListener('start',()=>{cameraDestination=null;targetDestination=null;qa.view='orbit';for(const b of document.querySelectorAll('[data-view]'))b.setAttribute('aria-pressed','false');});
function resize(){const w=stage.clientWidth,h=stage.clientHeight;if(w<1||h<1)return;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false);controls.minDistance=height*.85;controls.maxDistance=height*4;setView(activeView,true);qa.viewport={width:w,height:h,pixelRatio:renderer.getPixelRatio()};}
const resizeObserver=new ResizeObserver(resize);resizeObserver.observe(stage);resize();
const ref=query.get('ref');if(ref&&ref.startsWith('/assets/')&&!ref.startsWith('//')){$('#reference-image').src=ref;$('#reference-link').href=ref;$('#reference-image').addEventListener('load',()=>$('#reference').classList.add('visible'));}
Object.assign(qa,{scene,camera,renderer,controls,selectAnimation,setAnimation:selectAnimation,setView,setPaused,setAutoRotate,resize,getClip:name=>clips.get(name)??null});
async function load(){try{const gltf=await new GLTFLoader().loadAsync(modelURL,progress=>{if(progress.total)$('#loading-detail').textContent=`加载模型 ${Math.round(progress.loaded/progress.total*100)}%`;});model=gltf.scene;scene.add(model);model.updateMatrixWorld(true);const initialBounds=new THREE.Box3().setFromObject(model),size=initialBounds.getSize(new THREE.Vector3()),center=initialBounds.getCenter(new THREE.Vector3());height=size.y;width=Math.max(size.x,size.z);model.position.add(new THREE.Vector3(-center.x,-initialBounds.min.y,-center.z));model.updateMatrixWorld(true);let triangles=0,meshCount=0;model.traverse(o=>{if(!o.isMesh)return;o.castShadow=true;o.receiveShadow=true;meshCount++;const geometry=o.geometry;triangles+=(geometry.index?geometry.index.count:geometry.attributes.position.count)/3;});mixer=new THREE.AnimationMixer(model);procedural=!gltf.animations.length;clips=procedural?new Map(['Idle','Walk','Sitting','Typing'].map(name=>[name,new THREE.AnimationClip(name,1,[])])):new Map(gltf.animations.map(clip=>[clip.name,seatedLifeClip(clip,character.id)]));mixer.addEventListener('finished',event=>{if(event.action!==action)return;transition=false;qa.transitioning=false;play(desired);});qa.clipNames=[...clips.keys()];qa.availableAnimations=['Idle','Walk','Sitting','Typing','Agree'].filter(name=>actualClip(name));qa.model=model;qa.mixer=mixer;qa.modelBounds={min:initialBounds.min.toArray(),max:initialBounds.max.toArray(),height,width};qa.triangles=triangles;qa.meshCount=meshCount;for(const option of $('#animation').options){option.disabled=!actualClip(option.value);if(option.disabled)option.textContent+=' · 暂无';}$('#animation').disabled=false;$('#pause').disabled=false;$('#clip-count').textContent=`${procedural?4:gltf.animations.length} CLIPS`;$('#animation-total').textContent=`${gltf.animations.length} 个`;$('#model-height').textContent=`${height.toFixed(2)} m`;$('#triangle-count').textContent=Math.round(triangles).toLocaleString('zh-CN');const unavailable=['Walk','Sitting','Agree'].filter(name=>!actualClip(name));$('#animation-notice').textContent=unavailable.length?'部分动作尚未包含在此模型中':character.animationNotice||'可预览待机、行走、入座与打字';$('#download').href=modelURL;$('#download').setAttribute('aria-disabled','false');const start=actualClip('Idle')?'Idle':qa.availableAnimations[0];if(start)selectAnimation(start);mixer.update(0);resize();loaded=true;qa.status='ready';qa.loadedAt=performance.now();$('#loading').hidden=true;renderer.render(scene,camera);qa.ready=true;}catch(error){fail(error);}}
function frame(now){requestAnimationFrame(frame);try{const dt=Math.min((now-last)/1000,.05);last=now;if(document.hidden)return;if(loaded&&!paused){mixer.update(dt);qa.animationFrames++;qa.animationTime=action?.time??0;if(procedural){const t=qa.animationTime,phase=t*Math.PI*2;const seated=desired==='Sitting'||desired==='Typing';model.position.y=(seated?-0.08:0)+ (desired==='Idle'?Math.sin(phase)*0.004:0);model.rotation.z=desired==='Walk'?Math.sin(phase)*0.025:desired==='Typing'?Math.sin(phase*2)*0.008:0;model.rotation.y=desired==='Walk'?Math.sin(phase)*0.03:0;}}if(cameraDestination){camera.position.lerp(cameraDestination,1-Math.exp(-dt*8));controls.target.lerp(targetDestination,1-Math.exp(-dt*8));if(camera.position.distanceTo(cameraDestination)<.003){camera.position.copy(cameraDestination);controls.target.copy(targetDestination);cameraDestination=null;targetDestination=null;}}controls.update(dt);renderer.render(scene,camera);qa.frames++;qa.renderCount=qa.frames;qa.lastFrameAt=now;qa.cameraPosition=camera.position.toArray();}catch(error){if(qa.status!=='error')fail(error);}}
requestAnimationFrame(frame);load().then(()=>{if(loaded&&character.animationNotice)$('#animation-notice').textContent=character.animationNotice;});
